In [2]:
import pandas as pd

# Landsat Feature Extraction

In [3]:
df_landsat_features_train = pd.read_csv("landsat_features_training_all_bands_nonnull.csv")
display(df_landsat_features_train.head(5))

,latitude,longitude,sample date,emis,atran,swir16,atmos_opacity,green,drad,red,swir22,emsd,cdist,nir08,blue,trad,lwir,urad
0,-28.760833,17.730278,02-01-2011,9880.0,7669.0,7687.5,8.0,11426.0,890.0,12802.0,7645.0,57.000000,2447.5,11190.0,9557.0,8935.0,44344.0,1835.0
1,-26.861111,28.884722,03-01-2011,9570.5,7957.5,13746.5,46.0,9550.0,747.0,9241.5,10574.0,-1788.193154,476.5,17658.5,8691.0,9097.0,45396.5,1477.5
2,-26.450000,28.085833,03-01-2011,9670.5,9051.0,17974.0,9.0,10720.0,329.0,12540.0,14201.0,89.500000,178.5,15210.0,9502.5,7739.0,41467.5,590.0
3,-27.671111,27.236944,03-01-2011,9756.5,6476.0,13522.0,48.0,10943.0,1198.0,11237.5,11403.0,96.500000,381.5,14887.0,9693.5,8990.0,46121.0,2550.0
4,-27.356667,27.286389,03-01-2011,9829.5,6521.0,12665.5,106.5,9502.5,1187.0,9290.0,9643.0,95.000000,930.0,16828.5,8718.0,8547.0,44381.0,2526.0

In [3]:
df_landsat_features_val = pd.read_csv("landsat_features_validation_all_bands_nonnull.csv")
display(df_landsat_features_val.head(5))

,latitude,longitude,sample date,lwir,green,cdist,blue,swir22,drad,atmos_opacity,urad,trad,emis,emsd,nir08,atran,red,swir16
0,-32.043333,27.822778,01-09-2014,46019.000000,12868.0,4275.5,11282.0,12421.0,441.0,8.00,821.0,7226.5,9704.0,39.0,15229.000000,8729.0,13210.0,14797.0
1,-33.329167,26.077500,16-09-2015,42072.949605,9019.7,2021.8,8164.7,9322.0,-4676.5,9.00,-4355.0,-702.0,9804.6,59.0,13127.000000,-827.5,9139.7,11053.2
2,-32.991639,27.640028,07-05-2015,20766.500000,9304.5,955.5,8111.5,9958.0,653.0,-804.75,1302.0,9005.5,9837.0,47.0,16221.000000,8352.0,9145.0,12536.5
3,-34.096389,24.439167,07-02-2012,46607.000000,8339.7,279.3,7816.0,8787.0,907.2,71.00,1896.8,9162.2,9761.8,36.2,14525.076258,7658.6,8058.7,10690.6
4,-32.000556,28.581667,01-10-2014,43152.129862,11100.5,738.5,9504.0,8711.0,778.0,64.00,1577.5,9074.5,9824.0,39.0,9125.000000,7928.5,11166.0,9455.0

In [5]:
df_dict = {
    "training": df_landsat_features_train
    , "validation": df_landsat_features_val
}

for df_type in df_dict.keys():
    df_processing = df_dict[df_type]
    ## Vegetation Index (NVDI)
    df_processing["NVDI"] = (df_processing["nir08"] - df_processing["red"]) / (df_processing["nir08"] + df_processing["red"])

    ## Soil Adjusted Vegetation Index (SAVI)
    L = 0.5
    df_processing["SAVI"] = ((df_processing["nir08"] - df_processing["red"]) / (df_processing["nir08"] + df_processing["red"] + L)) * (1 + L)
    ## Bare Soil Index (BSI)
    df_processing["BSI"] = (((df_processing["swir16"] + df_processing["red"]) - (df_processing["nir08"] + df_processing["blue"]))
                            / ((df_processing["swir16"] + df_processing["red"]) + (df_processing["nir08"] + df_processing["blue"])))
    ## Build-Up Index (NDBI)
    df_processing["NDBI"] = (df_processing["swir16"] - df_processing["nir08"]) / (df_processing["swir16"] + df_processing["nir08"])

    ## Tasseled Cap (TC) Wetness Index (TCWI)
    df_processing["TCWI"] = (0.1511 * df_processing["blue"]
                             + 0.1973 * df_processing["green"]
                             + 0.3283 * df_processing["red"]
                             + 0.3407 * df_processing["nir08"]
                             - 0.7117 * df_processing["swir16"]
                             - 0.4559 * df_processing["swir22"])

    df_processing.to_csv(f"data/landsat/landsat_features_{df_type}_ross.csv", index=False)

In [1]:
df_train = pd.read_csv(f"landsat_features_training_ross.csv")
df_train.isna().sum()

NameError: name 'pd' is not defined

In [8]:
df_val = pd.read_csv(f"landsat_features_validation_ross.csv")
df_val.isna().sum()

latitude         0
longitude        0
sample date      0
lwir             0
green            0
cdist            0
blue             0
swir22           0
drad             0
atmos_opacity    0
urad             0
trad             0
emis             0
emsd             0
nir08            0
atran            0
red              0
swir16           0
NVDI             0
SAVI             0
BSI              0
NDBI             0
TCWI             0
dtype: int64

In [9]:
df_val

,latitude,longitude,sample date,lwir,green,cdist,blue,swir22,drad,atmos_opacity,...,emsd,nir08,atran,red,swir16,NVDI,SAVI,BSI,NDBI,TCWI
0,-32.043333,27.822778,01-09-2014,46019.000000,12868.0,4275.5,11282.0,12421.0,441.0,8.000000,...,39.0,15229.000000,8729.0,13210.0,14797.0,0.070994,0.106489,0.027440,-0.014388,-2424.828900
1,-33.329167,26.077500,16-09-2015,42072.949605,9019.7,2021.8,8164.7,9322.0,-4676.5,9.000000,...,59.0,13127.000000,-827.5,9139.7,11053.2,0.179070,0.268599,-0.026487,-0.085764,-1630.256850
2,-32.991639,27.640028,07-05-2015,20766.500000,9304.5,955.5,8111.5,9958.0,653.0,-804.750000,...,47.0,16221.000000,8352.0,9145.0,12536.5,0.278956,0.418426,-0.057613,-0.128123,-1871.855550
3,-34.096389,24.439167,07-02-2012,46607.000000,8339.7,279.3,7816.0,8787.0,907.2,71.000000,...,36.2,14525.076258,7658.6,8058.7,10690.6,0.286328,0.429483,-0.087412,-0.152067,-1193.708219
4,-32.000556,28.581667,01-10-2014,43152.129862,11100.5,738.5,9504.0,8711.0,778.0,64.000000,...,39.0,9125.000000,7928.5,11166.0,9455.0,-0.100586,-0.150876,0.050752,0.017761,-299.600050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,-33.771111,25.386667,06-12-2012,47168.500000,9492.0,142.5,8542.0,10235.0,1554.0,10.000000,...,96.0,17562.000000,5979.0,9201.0,13559.5,0.312409,0.468605,-0.068424,-0.128609,-2148.903150
196,-33.185361,27.390750,04-09-2014,43632.166667,9083.5,1960.5,8045.0,9484.0,608.0,43.000000,...,80.0,15883.000000,8285.0,8931.5,12135.5,0.280139,0.420199,-0.063585,-0.133751,-1609.267350
197,-32.043333,27.822778,28-09-2015,42962.500000,10046.5,2035.0,8825.5,10969.0,531.0,8.400000,...,39.0,13619.500000,8741.0,10108.0,13105.0,0.147993,0.221985,0.016821,-0.019252,-3053.268050
198,-33.001667,25.161389,08-01-2015,44290.750000,10670.0,7281.5,9505.0,14835.5,1268.0,8.500001,...,52.0,13955.500000,6837.0,11638.0,17303.5,0.090550,0.135823,0.104595,0.107105,-6961.614650
199,-33.237780,26.994720,27-03-2013,44564.000000,10792.0,1167.0,9383.0,9639.0,396.0,9.000000,...,61.0,12451.626069,9043.0,11366.5,10398.0,0.045559,0.068337,-0.001608,-0.089876,-273.752848